name: CI/CD Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Copy .env.example to .env
        run: |
          cp .env .env || true

      - name: Build and run containers
        run: |
          docker compose build
          docker compose up -d
          sleep 15 # Đợi các service khởi động

      - name: Kiểm tra backend healthcheck (tuỳ chọn)
        run: |
          curl --fail http://localhost:8000/docs || (docker compose logs && exit 1)

      - name: Kiểm tra frontend qua nginx (tuỳ chọn)
        run: |
          curl --fail http://localhost/web/ || (docker compose logs && exit 1)

      - name: Dọn dẹp
        if: always()
        run: docker compose down -v