name: CI/CD - Telemedicine

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build backend image
        run: |
          docker build -t telemedicine-backend ./backend

      - name: Build frontend image
        run: |
          docker build -t telemedicine-frontend ./frontend

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/telemedicine_project
            git pull origin main
            docker compose down -v
            docker compose up -d --build
