name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: telemedicine_db
          POSTGRES_USER: telemedicine_user
          POSTGRES_PASSWORD: your_secure_password_here
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install backend dependencies
        working-directory: backend
        run: |
          pip install -r requirements.txt

      - name: Run backend tests
        working-directory: backend
        env:
          DATABASE_URL: postgresql://telemedicine_user:your_secure_password_here@localhost:5432/telemedicine_db
        run: |
          # chạy lệnh test hoặc kiểm tra khởi động API
          uvicorn main:app --host 0.0.0.0 --port 8000 & sleep 10
          curl http://localhost:8000 || exit 1

      - name: Install frontend dependencies
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/build

